config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: "tasks#index"
  get "task/:id", to: "tasks#show", as: :task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

def show
  @task = Task.find(params[:id])
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "https://use.fontawesome.com/releases/v5.5.0/css/all.css" , media: 'all'%>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<ul>
  <% @tasks.each do |task| %>
  <div class="items">
    <% if task.completed %>
    <i class="far fa-check-square"></i>
    <% else %>
    <i class="far fa-square"></i>
    <% end %>
    <li><%= link_to task.title, task_path(task) %></li>
  </div>
  <% end %>
</ul>

<hr>
<div class="add-task">
  <i class="fas fa-plus"></i>
  <p>Add new task</p>
</div>
<hr>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<div class="description">
  <p><%= @task.details %></p>
</div>

<div class="checkbox">
  <% if @task.completed %>
    <i class="far fa-check-square"></i>
    <% else %>
    <i class="far fa-square"></i>
    <% end %>
  <p>This task is <%= @task.completed ? "completed" : "not completed yet"%></p>
</div>

<%= link_to "Back to list", tasks_path %>